### ISSUE TITLE
Can we adapt the BLM model on source code?

### ISSUE THREAD

**Issue by antonio-mastropaolo** [Varal7/blank_language_model#2]
Hi everybody,

I'm trying to adapt the blank language model on source code since in my opinion, there are many code-related tasks where such a model con gives us astonishing results. When we deal with source code, one of the main limitations is the _open-vocabulry_ problem. 
Do you think it is doable to plug in a fully-fledged BLP/Sentencepiece model to cope with such a problem without altering the under-the-hood network?
Just for the record, I tried to increase the vocabulary size but, the number of UNK tokens I get, hinder the learning process by a lot.

Thank you  :)

**Comment by Varal7** [comment]
Hi,

Absolutely. You can preprocess the input with your favorite tokenizer and run the code as is. 

For instance, using Google's [SentencePiece](https://github.com/google/sentencepiece):

```
spm_encode --model=<model_file> --output_format=piece < train.txt > train.sp
spm_encode --model=<model_file> --output_format=piece < valid.txt > valid.sp
python train.py --train.sp --valid valid.sp --root_dir <checkpoint_root> --vocab_size 10000 -- model_type blm
```

In our experiments, we used [BPE](https://github.com/rsennrich/subword-nmt), to preprocess our data.
The calculation of the perplexity is handled by carefully keeping track of the true number of words (https://github.com/Varal7/blank_language_model/blob/release/dataset.py#L13).

```
subword-nmt learn-bpe -s 40000 < train.txt > codes
subword-nmt apply-bpe -c codes < train.txt> train.bpe
subword-nmt apply-bpe -c codes < valid.txt> valid.bpe
python train.py --train.sp --valid valid.sp --root_dir <checkpoint_root> --vocab_size 10000 -- model_type blm
```

One thing to be careful about is that when testing on an input with given blanks, you should prevent the tokenizer from touching breaking the  `<blank>` string.

```
subword-nmt apply-bpe -c codes --glossaries "<blank>" < input.txt > input.bpe
```

**Comment by antonio-mastropaolo** [comment]
@Varal7 Thank you very much for your detailed explanation, nothing more to add.

Have a good day :)
