### ISSUE TITLE
Speed-up the filling process

### ISSUE THREAD

**Issue by antonio-mastropaolo** [Varal7/blank_language_model#3]
Hi Guys,

I was wondering if there is a way to speed up the filling process when testing the model.
I found out that even if I change the number of available GPUs, actually it does not seems to work
'''
Last few lines of test.py

cuda = not args.no_cuda and torch.cuda.is_available()
device = torch.device('cuda' if cuda else 'cpu')
args.gpus = 3 if cuda else 0
'''

Any ideas?

Thank you in advance ;)

**Comment by shentianxiao** [comment]
Hi,

Changing args.gpus will only be effective for evaluating losses, where it's passed to the PyTorch Lightning framework (https://github.com/Varal7/blank_language_model/blob/release/test.py#L26).
We currently haven't implemented generation in PyTorch Lightning.

As an alternative, you may split the inputs and fill them in parallel.

**Comment by antonio-mastropaolo** [comment]
Ook I see, thank you for your quick reply!
