### ISSUE TITLE
Beam search code?

### ISSUE THREAD

**Issue by ghost** [Varal7/blank_language_model#6]
Hi, it looks like there's no option to run beam search during decoding. Would you be willing to release code for computing BLEU results on the Yahoo Answers dataset (which I assume uses beam search)? Thanks in advance.

**Comment by Varal7** [comment]
Hi, there are no plans to release and maintain code for beam search. 
You can look at this implementation and adapt it to make it work with the current version of the code:

https://github.com/Varal7/blank_language_model/blob/f479ba3cb55044ae54bb99b9bf83851823a041c9/test.py

**Comment by ghost** [comment]
I see, thanks for the link—will figure it out.
