### ISSUE TITLE
how to fill different options to a <blank>?

### ISSUE THREAD

**Issue by usccolumbia** [Varal7/blank_language_model#7]
python test.py --checkpoint checkpoints/yelp/neg/blm/lightning_logs/version_0/checkpoints/epoch\=???.ckpt \
--fill data/yelp/blank/test.1.blank --output test.1.tsf

I used the above script to fill blank. But it always creates the same fillings.
How to generate different feasible fillings?

**Comment by Varal7** [comment]
Bu default, we use `--decode greedy`. You can use ``--decode sample`` if you want diverse fillings.
