### ISSUE TITLE
Is there anyway to do only 1-to-1 blank filling without expanding?

### ISSUE THREAD

**Issue by usccolumbia** [Varal7/blank_language_model#8]
Is there anyway to do only 1-to-1 blank filling without expanding?

example:
I am used to \<blank\>  at \<blank\>.

-->I am used to reading at night.    (Good)

-->I am used to reading books at every night.   (Bad).

--> I want the filling only replaces each <blank> with a word without adding additional <blank> or more than one word.
so the total number of words is kept the same.

how to do this?

**Comment by Varal7** [comment]
Hi, you can try the Insertion Transformer for this purpose: https://arxiv.org/abs/1902.03249
